# Generated by Django 3.2 on 2023-06-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='titel',
            new_name='title',
        ),
    ]
